// Generated by kssrecomp.generated_blocks. Do not edit.
#pragma once
#include "kss/dispatcher.hpp"
#include <cstddef>
namespace kss::generated {
[[nodiscard]] bool register_reset_blocks(CheckedDispatcher& dispatcher);
[[nodiscard]] std::size_t reset_block_count() noexcept;
} // namespace kss::generated
