"""Deterministic C++ block-stub emission for early integration proofs."""

from __future__ import annotations

from .cfg import ControlFlowGraph


LIFTED_V1_OPCODES = frozenset({
    0xEA, 0x18, 0x38, 0x58, 0x78, 0xB8, 0xD8, 0xF8, 0xFB,
    0xC2, 0xE2, 0xA9, 0xA2, 0xA0, 0x8D, 0x8E, 0x8C, 0x9C,
    0x80, 0x4C,
    0x9A, 0x4B, 0xAB, 0xF4, 0x2B, 0x85, 0x64,
})


def emit_cpp(graph: ControlFlowGraph) -> str:
    lines = [
        "// Generated by kssrecomp. Do not edit.",
        "#include <cstdint>",
        '#include "kss/lifted_execution.hpp"',
        '#include "kss/scheduler.hpp"',
        "",
        "namespace kss::generated {",
        "",
    ]
    ordered = sorted(
        graph.blocks.items(),
        key=lambda item: (item[0].processor.value, item[0].pc, item[0].mode.key),
    )
    for identity, block in ordered:
        lines.append(f"void {identity.symbol}(CpuContext& cpu, Bus& bus, Scheduler&) {{")
        for insn in block.instructions:
            raw = " ".join(f"{byte:02X}" for byte in insn.bytes_)
            lines.append(f"  // ${insn.pc:06X}: {raw:<11} {insn.mnemonic}")
            if insn.opcode in LIFTED_V1_OPCODES:
                operands = list(insn.operand) + [0] * (3 - len(insn.operand))
                operand_cpp = ", ".join(f"0x{value:02X}" for value in operands)
                lines.append(
                    "  if (execute_lifted(cpu, bus, "
                    f"LiftedInstruction{{0x{insn.opcode:02X}, {{{operand_cpp}}}, "
                    f"{len(insn.operand)}}}).status != LiftStatus::executed) {{"
                )
                lines.append("    cpu.stopped = true;")
                lines.append("    return;")
                lines.append("  }")
            else:
                lines.append("  // Semantics not lifted in v1; block remains non-executable here.")
                lines.append("  cpu.stopped = true;")
                lines.append("  return;")
        lines.append("}")
        lines.append("")
    lines.extend(("}  // namespace kss::generated", ""))
    return "\n".join(lines)
