"""Deterministic C++ block-stub emission for early integration proofs."""

from __future__ import annotations

from .cfg import ControlFlowGraph


def emit_cpp(graph: ControlFlowGraph) -> str:
    lines = [
        "// Generated by kssrecomp. Do not edit.",
        "#include <cstdint>",
        '#include "recomp/cpu_context.hpp"',
        "",
        "namespace kss::generated {",
        "",
    ]
    ordered = sorted(
        graph.blocks.items(),
        key=lambda item: (item[0].processor.value, item[0].pc, item[0].mode.key),
    )
    for identity, block in ordered:
        lines.append(f"void {identity.symbol}(CpuContext& cpu, Bus& bus) {{")
        lines.append("  (void)cpu;")
        lines.append("  (void)bus;")
        for insn in block.instructions:
            raw = " ".join(f"{byte:02X}" for byte in insn.bytes_)
            lines.append(f"  // ${insn.pc:06X}: {raw:<11} {insn.mnemonic}")
        lines.append("}")
        lines.append("")
    lines.extend(("}  // namespace kss::generated", ""))
    return "\n".join(lines)
