"""Emit bounded, deterministic C++ registration from a lifted reset CFG."""

from __future__ import annotations

import argparse
from collections import deque
import hashlib
import json
from pathlib import Path
from typing import Any, Mapping


class GeneratedBlocksError(ValueError):
    """The lifted artifact cannot safely be turned into executable blocks."""


def _mode_key(mode: Mapping[str, Any]) -> tuple[bool, bool, bool]:
    return bool(mode["emulation"]), bool(mode["m8"]), bool(mode["x8"])


def _identity_key(identity: Mapping[str, Any]) -> tuple[str, int, bool, bool, bool]:
    e, m, x = _mode_key(identity["mode"])
    return str(identity["processor"]), int(identity["pc"]), e, m, x


def _symbol(identity: Mapping[str, Any]) -> str:
    processor, pc, e, m, x = _identity_key(identity)
    return f"block_{processor}_{pc:06x}_e{int(e)}m{int(m)}x{int(x)}"


def _cpp_key(identity: Mapping[str, Any]) -> str:
    processor, pc, e, m, x = _identity_key(identity)
    pid = "ProcessorId::snes_cpu" if processor == "scpu" else "ProcessorId::sa1"
    return f"BlockKey::make({pid}, 0x{pc:06X}U, {str(e).lower()}, {str(m).lower()}, {str(x).lower()})"


def select_blocks(document: Mapping[str, Any], max_blocks_per_processor: int) -> list[Mapping[str, Any]]:
    if document.get("schema_version") != 1:
        raise GeneratedBlocksError("unsupported lifted reset CFG schema version")
    if not 1 <= max_blocks_per_processor <= 4096:
        raise GeneratedBlocksError("max_blocks_per_processor must be between 1 and 4096")
    blocks = document.get("blocks")
    edges = document.get("edges")
    regions = document.get("regions")
    if not isinstance(blocks, list) or not isinstance(edges, list) or not isinstance(regions, dict):
        raise GeneratedBlocksError("lifted reset CFG is missing blocks, edges, or regions")
    by_key: dict[tuple[str, int, bool, bool, bool], Mapping[str, Any]] = {}
    outgoing: dict[tuple[str, int, bool, bool, bool], list[tuple[str, int, bool, bool, bool]]] = {}
    for block in blocks:
        key = _identity_key(block["identity"])
        if key in by_key:
            raise GeneratedBlocksError(f"duplicate block identity: {key}")
        by_key[key] = block
        outgoing[key] = []
    for edge in edges:
        source = _identity_key(edge["source"])
        target = _identity_key(edge["target"])
        if source[0] != target[0]:
            raise GeneratedBlocksError("edge crosses processors")
        if source not in by_key or target not in by_key:
            raise GeneratedBlocksError("edge references a missing block")
        outgoing[source].append(target)

    selected: list[Mapping[str, Any]] = []
    for processor in ("scpu", "sa1"):
        try:
            entry = _identity_key(regions[processor]["entry"])
        except (KeyError, TypeError) as error:
            raise GeneratedBlocksError(f"missing {processor} entry") from error
        if entry not in by_key:
            raise GeneratedBlocksError(f"{processor} entry is not a block")
        pending = deque([entry])
        seen: set[tuple[str, int, bool, bool, bool]] = set()
        while pending and len(seen) < max_blocks_per_processor:
            key = pending.popleft()
            if key in seen:
                continue
            seen.add(key)
            block = by_key[key]
            # Unresolved nodes are deliberately not registered. Dispatching
            # them therefore fails closed as an unknown block.
            if block.get("status") == "decoded" and block.get("instruction") is not None:
                selected.append(block)
            for target in sorted(outgoing[key]):
                if target not in seen:
                    pending.append(target)
    selected.sort(key=lambda block: _identity_key(block["identity"]))
    return selected


def render(
    document: Mapping[str, Any], *, max_blocks_per_processor: int = 256,
    registration_name: str = "reset", header_include: str = "kss/generated_reset_blocks.hpp",
) -> tuple[str, str, dict[str, Any]]:
    if not registration_name.replace("_", "").isalnum() or not registration_name[0].isalpha():
        raise GeneratedBlocksError("registration_name must be a C++ identifier fragment")
    blocks = select_blocks(document, max_blocks_per_processor)
    outgoing: dict[tuple[str, int, bool, bool, bool], list[Mapping[str, Any]]] = {}
    for edge in document["edges"]:
        outgoing.setdefault(_identity_key(edge["source"]), []).append(edge["target"])
    header = """// Generated by kssrecomp.generated_blocks. Do not edit.
#pragma once
#include \"kss/dispatcher.hpp\"
#include <cstddef>
namespace kss::generated {
[[nodiscard]] bool register_%s_blocks(CheckedDispatcher& dispatcher);
[[nodiscard]] std::size_t %s_block_count() noexcept;
} // namespace kss::generated
""" % (registration_name, registration_name)
    source = [
        "// Generated by kssrecomp.generated_blocks. Do not edit.",
        f'#include "{header_include}"',
        '#include "kss/lifted_execution.hpp"',
        '#include "kss/sa1_timing.hpp"',
        "",
        "namespace kss::generated {",
        "namespace {",
    ]
    for block in blocks:
        identity = block["identity"]
        instruction = block["instruction"]
        raw = bytes.fromhex(instruction["bytes_hex"])
        operands = list(raw[1:]) + [0] * (3 - len(raw[1:]))
        source.extend([
            f"void {_symbol(identity)}(CpuContext& cpu, Bus& bus, Scheduler&) {{",
            f"    constexpr auto expected = {_cpp_key(identity)};",
            "    if (cpu.block_key() != expected) { cpu.stopped = true; return; }",
            "    const LiftedInstruction instruction{",
            f"        0x{raw[0]:02X}, {{{', '.join(f'0x{x:02X}' for x in operands)}}}, {len(raw) - 1}}};",
            "    observe_generated_instruction_fetches(",
            "        bus, cpu.processor, expected.address, instruction.operand_count);",
        ])
        if identity["processor"] == "sa1":
            source.extend([
                "    if (expected.address == 0x008BF4U && cpu.cycles == 0U) {",
                "        cpu.cycles += sa1_reset_release_origin_cycles();",
                "    }",
                "    const auto measured = lookup_sa1_reset_timing(expected.address, instruction.opcode);",
                "    const auto post_reset = lookup_sa1_post_reset_timing(expected.address, instruction.opcode);",
                "    const auto mvn_wait = lookup_sa1_reset_mvn_wait(",
                "        expected.address, instruction.opcode, cpu.a, cpu.x, cpu.y);",
                "    const auto post_reset_mvn_wait = lookup_sa1_post_reset_mvn_completion_wait(",
                "        expected.address, instruction.opcode, cpu.a, cpu.x, cpu.y);",
            ])
        source.extend([
            "    if (execute_lifted(cpu, bus, instruction).status != LiftStatus::executed) {",
            "        cpu.stopped = true;",
            "        return;",
            "    }",
        ])
        if identity["processor"] == "sa1":
            source.extend([
                "    if (measured) { cpu.cycles += measured->observed_wait_cycles; }",
                "    if (post_reset) { cpu.cycles += post_reset->observed_wait_cycles; }",
                "    if (mvn_wait) { cpu.cycles += *mvn_wait; }",
                "    if (post_reset_mvn_wait) { cpu.cycles += *post_reset_mvn_wait; }",
            ])
        successors = sorted(outgoing.get(_identity_key(identity), []), key=_identity_key)
        if successors:
            condition = " && ".join(f"cpu.block_key() != {_cpp_key(target)}" for target in successors)
            source.append(f"    if ({condition}) {{ cpu.stopped = true; }}")
        source.extend(["}", ""])
    source.extend(["} // namespace", "", f"bool register_{registration_name}_blocks(CheckedDispatcher& dispatcher) {{"])
    if blocks:
        source.append("    bool ok = true;")
        for block in blocks:
            source.append(
                f"    ok = dispatcher.register_block({_cpp_key(block['identity'])}, "
                f"&{_symbol(block['identity'])}) == RegistrationStatus::registered && ok;"
            )
        source.append("    return ok;")
    else:
        source.append("    return true;")
    source.extend([
        "}", "", f"std::size_t {registration_name}_block_count() noexcept {{ return {len(blocks)}U; }}",
        "", "} // namespace kss::generated", "",
    ])
    canonical = json.dumps(document, sort_keys=True, separators=(",", ":")).encode()
    counts = {processor: sum(b["identity"]["processor"] == processor for b in blocks)
              for processor in ("scpu", "sa1")}
    manifest = {
        "schema_version": 1,
        "generator": "kssrecomp.generated_blocks-v1",
        "input_sha256": hashlib.sha256(canonical).hexdigest(),
        "max_blocks_per_processor": max_blocks_per_processor,
        "registered_blocks": len(blocks),
        "processors": counts,
        "identity_policy": "processor-pc24-emulation-m8-x8",
        "failure_policy": "stop-on-lift-failure-omit-unresolved",
    }
    route_counts: dict[str, int] = {}
    for block in blocks:
        for route in block.get("routes", []):
            route_counts[route] = route_counts.get(route, 0) + 1
    if route_counts:
        manifest["route_provenance"] = {
            "policy": "coverage-route-ids-per-registered-identity",
            "registered_blocks_by_route": dict(sorted(route_counts.items())),
        }
    return header, "\n".join(source), manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("header", type=Path)
    parser.add_argument("source", type=Path)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--max-blocks", type=int, default=256)
    parser.add_argument("--registration-name", default="reset")
    parser.add_argument("--header-include", default="kss/generated_reset_blocks.hpp")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        document = json.loads(args.input.read_text(encoding="utf-8"))
        header, source, manifest = render(
            document, max_blocks_per_processor=args.max_blocks,
            registration_name=args.registration_name, header_include=args.header_include)
    except (OSError, json.JSONDecodeError, GeneratedBlocksError) as error:
        parser.error(str(error))
    outputs = ((args.header, header), (args.source, source),
               (args.manifest, json.dumps(manifest, indent=2, sort_keys=True) + "\n"))
    if args.check:
        stale = [str(path) for path, content in outputs
                 if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            parser.error("stale or missing generated output: " + ", ".join(stale))
        return 0
    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
